version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - db