# Generated by Django 3.2.16 on 2023-10-12 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.TimeField()),
                ('video', models.FileField(upload_to='media/exercises_video')),
                ('break_time', models.TimeField()),
                ('modified_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.FileField(null=True, upload_to='media/workout_image')),
                ('duration', models.TimeField()),
                ('calories', models.IntegerField()),
                ('available', models.BooleanField()),
                ('modified_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercises')),
            ],
        ),
    ]
